language: php

jobs:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4

matrix:
    fast_failure: true
    include:
        - dist: precise
          php: 5.3
          env: dependencies=lowest
        - dist: precise
          php: 5.4
          env: dependencies=lowest
        - php: 7.0
          env: SYMFONY_VERSION=2.7.x
        - php: 7.0
          env: SYMFONY_VERSION=2.8.x
        - php: 7.0
          env: SYMFONY_VERSION=3.0.x
        - php: 7.0
          env: SYMFONY_VERSION=3.1.x
        - php: hhvm
          env: SYMFONY_VERSION=3.4.x
        - php: 7.1
          env: SYMFONY_VERSION=4.0.x stability=beta
        - php: 7.2
          env: SYMFONY_VERSION=4.0.x stability=beta
        - php: 7.3
          env: SYMFONY_VERSION=4.0.x stability=beta
        - php: 7.4
          env: SYMFONY_VERSION=4.0.x stability=beta

# lock distro so new future defaults will not break the build
dist: trusty
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo 'memory_limit=-1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi;
  - if [ "$stability" != "" ]; then composer config minimum-stability $stability; fi;

install:
  - if [ -z "$dependencies" ]; then composer update  --dev --prefer-dist --no-interaction; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update  --dev --prefer-lowest --prefer-stable --prefer-dist --no-interaction; fi;

before_script:
  - |
    echo "TRAVIS_PHP_VERSION:" $TRAVIS_PHP_VERSION;
    php -v;
    php -r 'echo "PHP: ".PHP_VERSION."\n";';
    if [ $(echo "$TRAVIS_PHP_VERSION >= 7.2" | bc -l) -eq 1 ]; then
      echo using PHPUnit 7.5.2
      curl -sSfL -o ~/.phpenv/versions/$TRAVIS_PHP_VERSION/bin/phpunit https://phar.phpunit.de/phpunit-7.5.2.phar;
    fi
    
script: ./vendor/bin/phpunit --coverage-text

notifications:
  email: false