language: php

jobs:
  include:
    - php: 7.2.5
    - php: 7.3
    - php: 7.4

matrix:
    fast_failure: true
    include:
        - php: 7.2.5
          env: SYMFONY_VERSION=5.0.x stability=beta
        - php: 7.3
          env: SYMFONY_VERSION=5.0.x stability=beta
        - php: 7.4
          env: SYMFONY_VERSION=5.0.x stability=beta

# lock distro so new future defaults will not break the build
dist: trusty
sudo: false
cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit=-1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi;
  - if [ "$stability" != "" ]; then composer config minimum-stability $stability; fi;

install: composer update --prefer-dist --no-interaction

script: ./vendor/bin/phpunit --coverage-text

notifications:
  email: false